# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("exams", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="examsolution", name="exam"),
        migrations.AddField(
            model_name="examfile",
            name="solutions",
            field=models.BooleanField(
                default=False,
                help_text="Set this when the attached file contains worked solutions",
            ),
        ),
        migrations.DeleteModel(name="ExamSolution"),
    ]
