# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-02 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("exams", "0002_auto_20160511_1003")]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="student_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Set this to override the number of students writing (for sign-in sheets)",
                null=True,
            ),
        )
    ]
