# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-02 15:55
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("exams", "0003_exam_student_count")]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="exams.ExamType"
            ),
        ),
        migrations.AlterField(
            model_name="examlocation",
            name="location",
            field=models.ForeignKey(
                help_text='If you require a room not in this list, please contact <a href="mailto:a">D</a>',
                on_delete=django.db.models.deletion.PROTECT,
                to="places.ClassRoom",
            ),
        ),
    ]
