# Generated by Django 2.1.7 on 2019-03-11 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("exams", "0005_auto_20171017_1345")]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="dtstart",
            field=models.DateTimeField(
                help_text="Dates are YYYY-MM-DD.  Time is in 24-hour notation.",
                verbose_name="date and start time",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="sections",
            field=models.ManyToManyField(
                limit_choices_to={
                    "active": True,
                    "course__active": True,
                    "course__department__active": True,
                },
                to="classes.Section",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="type",
            field=models.ForeignKey(
                limit_choices_to={"active": True},
                on_delete=django.db.models.deletion.PROTECT,
                to="exams.ExamType",
            ),
        ),
        migrations.AlterField(
            model_name="examfile",
            name="exam",
            field=models.ForeignKey(
                help_text="For existing exams",
                limit_choices_to={"active": True},
                on_delete=django.db.models.deletion.CASCADE,
                to="exams.Exam",
            ),
        ),
        migrations.AlterField(
            model_name="examlocation",
            name="exam",
            field=models.ForeignKey(
                limit_choices_to={"active": True},
                on_delete=django.db.models.deletion.CASCADE,
                to="exams.Exam",
            ),
        ),
        migrations.AlterField(
            model_name="examlocation",
            name="location",
            field=models.ForeignKey(
                help_text='If you require a room not in this list, please contact <a href="mailto:e">w</a>',
                limit_choices_to={"active": True},
                on_delete=django.db.models.deletion.PROTECT,
                to="places.ClassRoom",
            ),
        ),
    ]
