# Generated by Django 2.1.7 on 2019-03-11 14:40

import exams.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("exams", "0006_auto_20190311_0929")]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="dtstart",
            field=models.DateTimeField(
                help_text="Dates are YYYY-MM-DD.  Time is in the 24-hour time notation.",
                validators=[exams.validators.validate_reasonable_time],
                verbose_name="date and start time",
            ),
        )
    ]
