# Generated by Django 2.2.1 on 2019-05-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("exams", "0008_auto_20190508_1133")]

    operations = [
        migrations.AlterField(
            model_name="examfile",
            name="public",
            field=models.BooleanField(
                choices=[(True, "Public"), (False, "Restricted")], default=False
            ),
        )
    ]
